sudo: required
services:
  - docker

before_install:
  - docker build -t react-client-tests -f ./client/Dockerfile.dev ./client/.

script:
  - docker run react-client-tests npm run test -- --coverage

after_success:
  # build all parts of app
  - docker build -t romangordienko/multitrack-client ./client
  - docker build -t romangordienko/multitrack-nginx ./nginx
  - docker build -t romangordienko/multitrack-server ./server
  - docker build -t romangordienko/multitrack-worker ./worker

  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # put builded images to docker hub
  - docker push romangordienko/multitrack-client
  - docker push romangordienko/multitrack-nginx
  - docker push romangordienko/multitrack-server
  - docker push romangordienko/multitrack-worker